package org.example.pantrypilot.model;

public enum ChatActionType {
    CREATE_PANTRY_ITEM,
    UPDATE_PANTRY_ITEM,
    DELETE_PANTRY_ITEM,
    CONSUME_PANTRY_ITEM,
    CREATE_SHOPPING_LIST,
    ADD_SHOPPING_LIST_ITEM,
    REMOVE_SHOPPING_LIST_ITEM,
    CHECK_SHOPPING_LIST_ITEM,
    UNCHECK_SHOPPING_LIST_ITEM,
    GENERATE_SHOPPING_LIST_FROM_RECIPE,
    CREATE_RECIPE,
    DELETE_RECIPE,
    ADD_RECIPE_INGREDIENT,
    REMOVE_RECIPE_INGREDIENT,
    BULK_ACTION
}
